# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licence', '0001_initial'),
        ('author', '0003_auto_20160108_0945'),
        ('instrument', '0001_initial'),
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(null=True)),
                ('branch', models.CharField(default=None, max_length=100, null=True)),
                ('hashCommit', models.CharField(max_length=100)),
                ('deprecated', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('lock', models.BooleanField(default=False)),
                ('tag', models.CharField(default=None, max_length=100, null=True)),
                ('author', models.CharField(default=None, max_length=100, null=True)),
                ('size', models.IntegerField(default=None, null=True, verbose_name='Taille')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashFile', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField(null=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Commit')),
                ('instrument', models.ManyToManyField(to='instrument.Instrument')),
                ('licence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licence.Licence')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='software.Software')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('url', models.CharField(max_length=1000, null=True, verbose_name='Url')),
                ('login', models.CharField(max_length=100, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(max_length=100, verbose_name='Mot de passe')),
                ('size', models.IntegerField(null=True, verbose_name='Taille')),
                ('gitlabId', models.IntegerField(null=True)),
                ('scoreAuthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='author.Author', verbose_name='Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
                ('dateUpload', models.DateTimeField(auto_now_add=True)),
                ('dateDelete', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Repository'),
        ),
    ]
