# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='login',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='password',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
    ]
