# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Repository', verbose_name='Dépot')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
        ),
        migrations.RemoveField(
            model_name='commit',
            name='tag',
        ),
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Branche', verbose_name='Dépot'),
        ),
        migrations.AddField(
            model_name='tag',
            name='commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Commit', verbose_name='Commit'),
        ),
    ]
