# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='hashCommit',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='hashFile',
            new_name='hash',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='gitlabId',
        ),
        migrations.AddField(
            model_name='repository',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.Branche', verbose_name='Branche'),
        ),
    ]
