# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20160209_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
