# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repository', '0003_downloaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaduser',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2016, 1, 10, 13, 37, 38, 118250, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
