# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20160214_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='commit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='repository.Commit', verbose_name='Commit'),
        ),
    ]
