# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20160105_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='deathDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date de décès'),
        ),
    ]
