# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='licence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='licence.Licence', verbose_name='Licence'),
        ),
    ]
